# Generated by Django 3.2.9 on 2022-01-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('location', models.CharField(max_length=250, verbose_name='location')),
                ('destination', models.CharField(max_length=250, verbose_name='destination')),
                ('tel_number', models.CharField(max_length=20, verbose_name='tel_number')),
                ('status', models.CharField(choices=[('simple', 'Simple'), ('middle', 'Middle'), ('lux', 'Lux')], default='simple', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('license_number', models.CharField(max_length=30)),
                ('car_number', models.CharField(max_length=30, verbose_name='car_number')),
                ('tel_number', models.CharField(max_length=20, verbose_name='tel_number')),
                ('status', models.CharField(choices=[('simple', 'Simple'), ('middle', 'Middle'), ('lux', 'Lux')], default='simple', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_order', models.CharField(choices=[('simple', 'Simple'), ('middle', 'Middle'), ('lux', 'Lux')], default='simple', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.CharField(default=False, max_length=10)),
                ('cancelled', models.CharField(default=False, max_length=10)),
                ('finished', models.CharField(default=False, max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='app_order.client')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='app_order.driver')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
