# Generated by Django 3.2.11 on 2022-01-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_auto_20220112_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_of_order',
            field=models.CharField(choices=[('Created', 'Created'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Finished', 'Finished')], default='Created', max_length=20),
        ),
    ]
